/* Auto-generated by genmsg_cpp for file /home/joschu/Dropbox/myros/snazzy_msgs/srv/GetUserCloud.srv */
#ifndef SNAZZY_MSGS_SERVICE_GETUSERCLOUD_H
#define SNAZZY_MSGS_SERVICE_GETUSERCLOUD_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "sensor_msgs/PointCloud2.h"


#include "sensor_msgs/PointCloud2.h"

namespace snazzy_msgs
{
template <class ContainerAllocator>
struct GetUserCloudRequest_ {
  typedef GetUserCloudRequest_<ContainerAllocator> Type;

  GetUserCloudRequest_()
  : cloud_in()
  {
  }

  GetUserCloudRequest_(const ContainerAllocator& _alloc)
  : cloud_in(_alloc)
  {
  }

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_in_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  cloud_in;


  typedef boost::shared_ptr< ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetUserCloudRequest
typedef  ::snazzy_msgs::GetUserCloudRequest_<std::allocator<void> > GetUserCloudRequest;

typedef boost::shared_ptr< ::snazzy_msgs::GetUserCloudRequest> GetUserCloudRequestPtr;
typedef boost::shared_ptr< ::snazzy_msgs::GetUserCloudRequest const> GetUserCloudRequestConstPtr;


template <class ContainerAllocator>
struct GetUserCloudResponse_ {
  typedef GetUserCloudResponse_<ContainerAllocator> Type;

  GetUserCloudResponse_()
  : cloud_out()
  {
  }

  GetUserCloudResponse_(const ContainerAllocator& _alloc)
  : cloud_out(_alloc)
  {
  }

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_out_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  cloud_out;


  typedef boost::shared_ptr< ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetUserCloudResponse
typedef  ::snazzy_msgs::GetUserCloudResponse_<std::allocator<void> > GetUserCloudResponse;

typedef boost::shared_ptr< ::snazzy_msgs::GetUserCloudResponse> GetUserCloudResponsePtr;
typedef boost::shared_ptr< ::snazzy_msgs::GetUserCloudResponse const> GetUserCloudResponseConstPtr;

struct GetUserCloud
{

typedef GetUserCloudRequest Request;
typedef GetUserCloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetUserCloud
} // namespace snazzy_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d6baad1c61b70905e9fb3abd9ede0480";
  }

  static const char* value(const  ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd6baad1c61b70905ULL;
  static const uint64_t static_value2 = 0xe9fb3abd9ede0480ULL;
};

template<class ContainerAllocator>
struct DataType< ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "snazzy_msgs/GetUserCloudRequest";
  }

  static const char* value(const  ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_msgs/PointCloud2 cloud_in\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d638895a709be2cef85df359cc39f0dc";
  }

  static const char* value(const  ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd638895a709be2ceULL;
  static const uint64_t static_value2 = 0xf85df359cc39f0dcULL;
};

template<class ContainerAllocator>
struct DataType< ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "snazzy_msgs/GetUserCloudResponse";
  }

  static const char* value(const  ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sensor_msgs/PointCloud2 cloud_out\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cloud_in);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetUserCloudRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cloud_out);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetUserCloudResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<snazzy_msgs::GetUserCloud> {
  static const char* value() 
  {
    return "d5f233284ec0b36be5d9f2701c1e3890";
  }

  static const char* value(const snazzy_msgs::GetUserCloud&) { return value(); } 
};

template<>
struct DataType<snazzy_msgs::GetUserCloud> {
  static const char* value() 
  {
    return "snazzy_msgs/GetUserCloud";
  }

  static const char* value(const snazzy_msgs::GetUserCloud&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d5f233284ec0b36be5d9f2701c1e3890";
  }

  static const char* value(const snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "snazzy_msgs/GetUserCloud";
  }

  static const char* value(const snazzy_msgs::GetUserCloudRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d5f233284ec0b36be5d9f2701c1e3890";
  }

  static const char* value(const snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "snazzy_msgs/GetUserCloud";
  }

  static const char* value(const snazzy_msgs::GetUserCloudResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // SNAZZY_MSGS_SERVICE_GETUSERCLOUD_H

